### ISSUE TITLE
localhost gets replaced by 127.0.0.1 silently for ssh connections

### ISSUE THREAD

**Issue by julian-weinert** [Sequel-Ace/Sequel-Ace#1326]
- Sequel Ace Version (including build number): 3.4.3 (20019)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.14.6
- Processor Type (Intel/Apple): Intel

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
The current Sequel Ace version replaces `localhost` silently with `127.0.0.1` without changing the host name field visibly.
I just ran into an issue where the hoster I'm trying to connect to only seems to have permissions for the MySQL user set on the literal "localhost" hostname.

Now Sequel Ace tries to connect to "user@127.0.0.1" and returns an access denied error.

**Steps To Reproduce**
1. Setup MySQL user with access to `localhost` (not 127.0.0.1)
2. Try connecting via SSH

**Expected Behaviour**
Open connection

**Related Issues**
https://github.com/Sequel-Ace/Sequel-Ace/issues/459

**Additional Context**
![Screenshot 2021-12-25 at 22 51 13](https://user-images.githubusercontent.com/3418452/147394149-a080d588-48f1-48b9-8991-920bea3b50d4.png)

**Comment by Jason-Morcos** [comment]
Last year we did this for TCP/IP connections but it does look like we didn't make the same change for SSH connections. I _believe_ this PR will allow it - after the PR is approved and merged, we'll release a beta you can try.
https://github.com/Sequel-Ace/Sequel-Ace/pull/1327

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by MACscr** [comment]
Issue still exists on 3.5.2, which was released in May. Is this fix still not released on the stable version?

**Comment by Jason-Morcos** [comment]
This has been fixed on the latest stable version. @MACscr Can you share a video demonstrating this occurring in the latest release?

**Comment by redgluten** [comment]
Hi sorry I cannot share a video at the moment but I can confirm the bug occurring with both 3.5.3 and 4.0 beta. It happens when connecting to a MariaDB 10.1.48 which I realise is pretty old and am not sure if it is supported at all. Thanks for the hard work anyway!

**Comment by klodeckl** [comment]
Same here. Sequel Ace 4.0.13. Is there any chance to get this fixed? I need localhost as host and not 127.0.0.1.

**Comment by verstratenbram** [comment]
This is still happening on Version 5.0.8 Build 20094. Why is this issue closed?
