### ISSUE TITLE
Incorrect units in tableinformation

### ISSUE THREAD

**Issue by jaapdevries** [Sequel-Ace/Sequel-Ace#518]
- Sequel Ace Version: 2.3.0
- macOS Version: 11.0.1 (Big Sur)

**Description**
The unit for auto_increment in table information in the lower left corner is incorrect.
It currently show **auto_increment: 3.911,0 MiB** instead of **auto_increment: 3.911**

<img width="244" alt="Schermafbeelding 2020-11-19 om 14 20 50" src="https://user-images.githubusercontent.com/39185570/99672005-20831800-2a73-11eb-8694-c47fd91e6a44.png">

**Comment by SumBeam** [comment]
This issue is fixed with this PR: #509

**Comment by Kaspik** [comment]
Duplicate: https://github.com/Sequel-Ace/Sequel-Ace/issues/504 and https://github.com/Sequel-Ace/Sequel-Ace/issues/477

**Comment by Kaspik** [comment]
Released 2.3.2 hotfix, available in the AppStore already.

**Comment by Rozkalns** [comment]
@Kaspik I have the latest version 2.3.2 downloaded from AppStore, but still not fixed
![image](https://user-images.githubusercontent.com/8157701/100846313-0986f180-3487-11eb-9712-1b291186d256.png)
![image](https://user-images.githubusercontent.com/8157701/100846372-1b689480-3487-11eb-8d95-3daae94e6139.png)
