### ISSUE TITLE
Can't connect via SSH to the database

### ISSUE THREAD

**Issue by sivajosyula** [Sequel-Ace/Sequel-Ace#755]
- Sequel Ace Version (including build number): 3.0.2 (3010)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1 (20C69)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.26
- macOS Localization: N/A

**Description**
I have been using Sequel Ace since the public release and recently update to version 3.0.2 (3010) from App Store. Ever since the update, when I try to connect to any of my AWS servers(SSH method), the APP crashes instantly. I am able to connect to Localhost(TCP/IP method) normally. 

**Steps To Reproduce**
1. Upgrade to latest on App Store as on 7th Jan 2021 -- Version 3.0.2 (3010).
2. Try to connect to Amazon RDS using EC2 SSH Host. 

**Expected Behaviour**
Expect it to connect to the database, just like it did before version 3.0.2 (3010).

**Comment by Kaspik** [comment]
Most of the SSH crashes are fixed in 3.1.0. Public beta is available, release will follow soon. Sorry for that!

**Comment by sivajosyula** [comment]
Thank you for the response. 

I don't think 3.1.0. Public beta is working. It does not crash on "_Connect_" but which I click on "_Connect_", the MySQL Password temporarily increases in number of characters and then it throws an error -- _SSH connection failed!_. The password reset itself to same number of character after closing out on the error message. 

Please let me know what else you need to help debug this.

**Comment by Kaspik** [comment]
The temporary change in password length is expected it means the password is changed to temporary one for security, and then SA uses password from Keychain.
Are you storing password in keychain? If so, do you actually see it in keychain, can you maybe remove it and set it again in SA so it's re-saved?

**Comment by sivajosyula** [comment]
It does pull from keychain and when I copy from keychain for Sequel Ace, I get the right password. I also tried manually replacing password in Beta and saving it, but same error.

I get this error on Beta -- _The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access._

With same credentials, I am able to connect from Sequel Pro.

**Comment by Kaspik** [comment]
Could you please try couple more things?

- try connecting from quick-connect by filling up all details manually - not from saved favorite at all
- if ^^ that works, then it's a problem with the favorite itself, so maybe deleting it and saving the quick connect as a favorite again?

Thanks!

**Comment by sivajosyula** [comment]
Just tried with "Quick Connect" and getting the same error.

**Comment by Jason-Morcos** [comment]
I just confirmed I am able to SSH to connections with 3.1.0. However, I use a private key and not a password. This sounds like the issue is in the SSH connection, not the MySQL connection. Are you authenticating via password or private key for SSH? Have you tried re-entering the SSH password/private in the favorite (not the MySQL password)?

**Comment by sivajosyula** [comment]
I am using RSA key to connect via SSH so the "_SSH Password_" field is always empty. I tried the same with cleartext plugin checked, but no change.

**Comment by sivajosyula** [comment]
FYI -- I just manually installed the latest stable version which was released few hours ago and initially it was not connecting. 

I got the _"stale"_ bookmark error as mentioned here - https://sequel-ace.com/ref/bookmarks.html#stale-security-scoped-bookmarks

Once I reselected the highlight record, I was able to connect normally. Beta still does not work but the stable version works after this minor selection. 

Hopefully this helps someone.
