### ISSUE TITLE
SSH Password auth Connection Fails on macOS <= 10.13 (due to lack of SwiftStandardLibraries)

### ISSUE THREAD

**Issue by carkar7** [Sequel-Ace/Sequel-Ace#777]
![Xnip2021-01-11_14-54-35](https://user-images.githubusercontent.com/22269536/104247656-0cc5b380-541d-11eb-830d-752b2623ae5d.jpg)

- Sequel Ace Version (3.1.0 3013):
- Sequel Ace Source (App Store):
- macOS Version:10.13.6 (17G4015)
- Processor Type (2.6 GHz Intel Core i7):
- MySQL Version: 5.8

**Description**
I just downloaded the update from app store and I can no longer access any database that uses an SSH password. Other databases that use an rsa key for SSH work fine

**Additional Context**
I've tried connecting through favorites and through quick connect, both throw out the same error. Able to connect directly via terminal

**Related Issues**
https://github.com/Sequel-Ace/Sequel-Ace/issues/755

**Comment by spaceman9** [comment]
Exactly the same issue here, it was been working great up til now, now the ssh connections just fail.

**Comment by jamesstout** [comment]
Will look asap

**Comment by spaceman9** [comment]
The issue is with Fix 299, Changing the UseKeyChain to no in the Resources/ssh_config file, stops sequel ace accessing the password for the ssh key.  If I manually change this line back to yes, then my ssh logins work ok.

**Comment by Jason-Morcos** [comment]
> The issue is with Fix 299, changing the UseKeyChain to no in the Resources/ssh_config file, stops sequel ace accessing the password for the ssh key.  If I manually change this line back to yes, then my ssh logins work ok.

This is not the issue. We made this change several months ago. That fix was key to Ace managing the keychain itself as opposed to falling back on default macOS password saving for ssh.

**Comment by spaceman9** [comment]
I reverted the UseKeyChain config option back to no, and it failed to connect again.  
However, I then checked console to see if there were any errors, and there is: 

`Process:               SequelAceTunnelAssistant [10835]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant
Identifier:            SequelAceTunnelAssistant
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ssh [10833]
Responsible:           SequelAceTunnelAssistant [10835]
User ID:               501

Date/Time:             2021-01-12 14:46:50.584 +0000
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        0365C47F-A971-DD66-337A-4A14C98329C4

Sleep/Wake UUID:       14917B86-2EEA-4D68-92A7-99C994521E99

Time Awake Since Boot: 41000 seconds
Time Since Wake:       24000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant
  Reason: image not found

Binary Images:
       0x10db95000 -        0x10db9cff7 +SequelAceTunnelAssistant (0) <493CFC7D-B03F-3E95-9340-DAF57705D01D> /Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant
       0x10ec36000 -        0x10ec80adf  dyld (551.5) <CB9BFB56-4511-36F1-A546-891FF770C01C> /usr/lib/dyld
    0x7fff46039000 -     0x7fff46e97fff  com.apple.AppKit (6.9 - 1561.61.100) <4E6EA3FA-8C2C-3B21-BFF9-6F8C458B7BE1> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff48a6c000 -     0x7fff48f08fff  com.apple.CoreFoundation (6.9 - 1455.300) <D9D5D50D-5DA3-34B6-8077-DD24315A4B1E> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4abe8000 -     0x7fff4afafffb  com.apple.Foundation (6.9 - 1455.300) <0479E072-1DD0-3881-A9A2-EDAD3EE58C23> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff5490e000 -     0x7fff54c39fff  com.apple.security (7.0 - 58286.70.19) <E118FC23-2E20-3999-826B-58488049A277> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff6e7cc000 -     0x7fff6e7cdffb  libSystem.B.dylib (1252.50.4) <5A02016C-8F9D-3F47-8C39-AD2CD4F9F11D> /usr/lib/libSystem.B.dylib
    0x7fff6f5ae000 -     0x7fff6f7d5ffb  libicucore.A.dylib (59181.0.1) <17767680-09DF-3954-AB6C-B13B41F92A2E> /usr/lib/libicucore.A.dylib
    0x7fff6ff07000 -     0x7fff702f83b7  libobjc.A.dylib (723) <616AB826-9179-3924-AA61-AF760363A3F5> /usr/lib/libobjc.A.dylib
`

**Comment by Jason-Morcos** [comment]
> Dyld Error Message:
> 
>   Library not loaded: @rpath/libswiftCore.dylib
> 
>   Referenced from: /Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant
> 
>   Reason: image not found

Sounds to me like an issue with us not embedding swift standard libraries. Perhaps the "Always Embed Swift Standard Libraries" flag just needs to be set to true in Xcode before next build.

**Comment by Kaspik** [comment]
I feel like we added the swift standard libraries in 3.1.1 - is this still an issue?

**Comment by MatzeKitt** [comment]
It’s still a problem for me in 3.1.1 (Build 3016).

**Comment by Jason-Morcos** [comment]
> It’s still a problem for me in 3.1.1 (Build 3016).

Do you have a different error in the console than the one @spaceman9 shared above and we believe we fixed (_Library not loaded: @rpath/libswiftCore.dylib_)?

**Comment by MatzeKitt** [comment]
How can I do this?

**Comment by Jason-Morcos** [comment]
> How can I do this?

Open the console app and look if you have any crashes, particularly for `SequelAceTunnelAssistant`. If so, grab the crash log and attach.

**Comment by MatzeKitt** [comment]
I couldn’t find any related.

The only one I found was this:

> identifier=com.sequel-ace.sequel-ace, pid=8708, auid=501, euid=501, binary_path=/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace attempted to call TCCAccessRequest for kTCCServiceAccessibility without the recommended com.apple.private.tcc.manager.check-by-audit-token entitlement

**Comment by spaceman9** [comment]
Morning, 

Sorry guys but the error is still the same 
v3.1.1 build 3016.

```
Process:               SequelAceTunnelAssistant [53021]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant
Identifier:            SequelAceTunnelAssistant
Version:               0
Code Type:             X86-64 (Native)
Date/Time:             2021-02-01 09:01:05.998 +0000
OS Version:            Mac OS X 10.13.6 (17G14042)
Exception Type:        EXC_CRASH (SIGABRT)
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant
  Reason: image not found

```
libswiftCore.dylib is definitely present in the Frameworks folder in the application

I'm no mac coder but I'm wondering if its something to do with the @rpath? Notice I'm using mac os 10.13, which is quite old now (this mac cannot be upgraded to a newer version)

**Comment by Kaspik** [comment]
Ohh, I haven't noticed the macOS 10.13 version. For this one, you need to install Swift support.

```
Swift command line projects won’t run on macOS 10.14.3 and earlier unless you install the Swift 5 Runtime Support for Command Line Tools package. Without that package, Swift command line projects crash on launch with “dyld: Library not loaded” errors. 
```

Could you please try that?

**Comment by spaceman9** [comment]
That works!

I downloaded the dmg, installed it.  I re-ran sequel ace, and it asked me for the password, and allowed me to login.  Fortunately I registered as a developer ages ago so it allowed me to download the tools.

**Comment by MatzeKitt** [comment]
Interestingly, for one of my hosts I get the following message:
<img width="481" alt="Bildschirmfoto 2021-02-01 um 11 30 44" src="https://user-images.githubusercontent.com/1018979/106446784-f5f50880-6480-11eb-9c2c-24f5770876d3.png">

The configuration is, besides credentials, identical to the other hosts where the first error message occurs.

**Comment by Kaspik** [comment]
If the message says this correct identifier than it's asking for password to unlock our Keychain. What if you allow it?

**Comment by MatzeKitt** [comment]
If I enter the password, I can connect to this particular host. However, I need to manually enter it every time.

**Comment by Jason-Morcos** [comment]
For the issue with swift libs in the tunnel assistant on macOS <10.14.4, would either of these ideas work for us to fix this without having users have to install the additional package from apple?
https://forums.swift.org/t/command-line-applications-crashes-with-xcode-10-2/22192/5
> There's no way to "embed" a shared library (dylib) inside a command line tool, since it's just a single file. If you want to handle the embedding-in-an-app case, you can manually set your tool's "Runpath Search Paths" to be able to find the dylibs that'll get embedded in the app. Make sure that the ones in /usr/lib/swift are still preferred, though, so that it'll run correctly on newer versions of macOS.
> I bundle swift command line tools with my apps, and I was able to work around this by pointing them to the Frameworks folder of my app bundle. If the command line tools are in your resources folder, you can point "Runpath Search Paths" to @executable_path/../Frameworks/.
I also needed to add an additional swift framework to my main bundle's frameworks. Dragging in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftSwiftOnoneSupport.dylib to the frameworks list did the trick. Running a test swift 5 command line tool in macOS 10.13 gave me a Hello, World!

**Comment by noplanman** [comment]
This is still a problem for me with the latest 3.2.2 release.

> you need to install Swift support.

@Kaspik, so you're saying that users need to install this as a pre-requesite?
Do you have a direct download link for the needed package?

**Comment by Kaspik** [comment]
Only users on macOS 10.14.3 and earlier, what's your version?

**Comment by Jason-Morcos** [comment]
@noplanman This is the direct download link - https://download.developer.apple.com/Developer_Tools/Swift_5_Runtime_Support_for_Command_Line_Tools/Swift_5_Runtime_Support_for_Command_Line_Tools.dmg


> Only users on macOS 10.14.3 and earlier, what's your version?

@Kaspik Is this not something we can fix so users don't have to download the package for our app to work? https://developer.apple.com/forums/thread/115020
<img width="1093" alt="Screen Shot 2021-02-21 at 16 00 10" src="https://user-images.githubusercontent.com/10710367/108643156-13a10680-745e-11eb-93c0-44a4c277449c.png">

**Comment by noplanman** [comment]
@Kaspik I'm on 10.13 High Sierra.
@Jason-Morcos That link leads to a Apple Developers only page, so I can't download it.
I sure hope this is something that can be fixed in this project.

At the moment my "solution" is to use an older version (3.0.1) which still works.

**Comment by Kaspik** [comment]
Added the install file to our repo to Scripts folder - https://github.com/Sequel-Ace/Sequel-Ace/blob/main/Scripts/Swift_5_Runtime_Support_for_Command_Line_Tools.dmg

You can now install it and use latest version on lower macOS than 10.14.4 :)

I think we won't be debugging other solution for now as we made this install file available...

**Comment by MatzeKitt** [comment]
Then my problem persists as I encounter it with macOS 11. 🙈

**Comment by noplanman** [comment]
@Kaspik Perfecto, thanks for the direct download, it's working now 🕺 

(maybe add this extra required step to the readme?)

**Comment by MatzeKitt** [comment]
For me it was working after switching back to v3.0.1 as @noplanman. Then, after trying to connect, I got this message:
<img width="260" alt="Bildschirmfoto 2021-02-22 um 12 48 25" src="https://user-images.githubusercontent.com/1018979/109174720-63950b80-7785-11eb-976d-412f2744608c.png">

And after successfully requesting access again it even worked after upgrading back to the current version. So for me, it seems that this check for the sandbox issue is broken on current versions since I didn’t get the message there.

**Comment by jpmurray** [comment]
Kept getting this error, and here's what's solving the issue for me : selecting again my private key. Doing this once on one of my connections solves the problem for the rest of them !

**Comment by Jason-Morcos** [comment]
> For me it was working after switching back to v3.0.1 as @noplanman. Then, after trying to connect, I got this message:
> <img alt="Bildschirmfoto 2021-02-22 um 12 48 25" width="260" src="https://user-images.githubusercontent.com/1018979/109174720-63950b80-7785-11eb-976d-412f2744608c.png">
> 
> And after successfully requesting access again it even worked after upgrading back to the current version. So for me, it seems that this check for the sandbox issue is broken on current versions since I didn’t get the message there.

@MatzeKitt @jpmurray Please open a separate issue :)
This issue specifically is about Swift runtime support in macOS 10.13. In this issue, ssh key connections work fine and password-only connections do not. That is not the issue you're describing.
I'll rename the issue to be clearer

**Comment by Kaspik** [comment]
As we added the install file here, I'll close this now.
